baseURL = "https://sboysel.github.io"
title = "Sam Boysel"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = false

[params]
description = ""
copyright = "Copyright © 2022 Sam Boysel"
dark = "auto"
highlight = true

[menu]
[[menu.main]]
identifier = "cv"
name = "cv"
title = "cv"
url = "/cv/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "projects"
title = "projects"
url = "/projects/"
weight = 20

# [[menu.main]]
# identifier = "posts"
# name = "posts"
# title = "posts"
# url = "/posts/"
# weight = 30



[permalinks]
posts = "/:title/"

[markup.goldmark.renderer]
# Allows HTML in Markdown
unsafe = true

[markup.goldmark.extensions]
footnote = true

[markup.highlight]
style = "solarized-dark"
codeFences = true
guessSyntax = true
hl_Lines = ''
hl_inline = false
lineAnchors = ''
noClasses = true
noHl = false
tabWidth = 4

